name: HomePlugin
version: '1.0-SNAPSHOT'
main: traiwy.homePlugin.HomePlugin
api-version: '1.20'
commands:
  sethome:
    usage: /sethome
  listhome:
    usage: /listhome
  home:
    usage: /home
  menuhome:
    usage: /menuhome